Added new env var

diff --git a/traefik/Makefile b/traefik/Makefile
--- a/traefik/Makefile
+++ b/traefik/Makefile
@@ -3,6 +3,8 @@ DOMAIN_NAME ?=
 ACME_FILE ?= ./acme.json
 HASHED_PASSWORD_ENV_VAR ?=
 CLOUDFLARE_API_KEY ?=
+CLOUDFLARE_EMAIL ?=
+CLOUDFLARE_DNS_API_TOKEN ?=
 
 # If HASHED_PASSWORD_ENV_VAR is not provided, prompt the user for a password
 ifndef HASHED_PASSWORD_ENV_VAR
@@ -10,13 +12,13 @@ define PASSWORD_PROMPT
 	@echo "No hashed password provided."; \
 	echo "Please enter a password for basic authentication:"; \
 	read -s password_input; \
-	 if [ -z "$$password_input" ]; then \
+	if [ -z "$$password_input" ]; then \
 	    echo "Error: No password provided."; \
 	    exit 1; \
-	 else \
+	else \
 	    HASHED_PASSWORD_ENV_VAR=$$(openssl passwd -apr1 "$$password_input" | sed -e 's/\$$/\\$$/g'); \
 	    echo "Password successfully hashed."; \
-	 fi
+	fi
 endef
 else
   PASSWORD_PROMPT=@echo "Using provided hashed password."
@@ -40,7 +42,7 @@ else
   DOMAIN_PROMPT=@echo "Using provided domain name: $(DOMAIN_NAME)"
 endif
 
-# If CF_API_TOKEN is not provided, prompt the user for it
+# If CLOUDFLARE_API_KEY is not provided, prompt the user for it
 ifndef CLOUDFLARE_API_KEY
 define CF_API_TOKEN_PROMPT
 	@echo "No Cloudflare API token provided."; \
@@ -58,15 +60,55 @@ else
   CF_API_TOKEN_PROMPT=@echo "Using provided Cloudflare API token."
 endif
 
+# If CLOUDFLARE_EMAIL is not provided, prompt the user for it
+ifndef CLOUDFLARE_EMAIL
+define CF_EMAIL_PROMPT
+	@echo "No Cloudflare email provided."; \
+	echo "Please enter the Cloudflare email:"; \
+	read cf_email_input; \
+	if [ -z "$$cf_email_input" ]; then \
+		echo "Error: No Cloudflare email provided."; \
+		exit 1; \
+	else \
+		CLOUDFLARE_EMAIL=$$cf_email_input; \
+		echo "Cloudflare email successfully set."; \
+	fi
+endef
+else
+  CF_EMAIL_PROMPT=@echo "Using provided Cloudflare email: $(CLOUDFLARE_EMAIL)"
+endif
+
+# If CLOUDFLARE_DNS_API_TOKEN is not provided, prompt the user for it
+ifndef CLOUDFLARE_DNS_API_TOKEN
+define CF_DNS_TOKEN_PROMPT
+	@echo "No Cloudflare DNS API token provided."; \
+	echo "Please enter the Cloudflare DNS API token:"; \
+	read -s cf_dns_token_input; \
+	if [ -z "$$cf_dns_token_input" ]; then \
+		echo "Error: No Cloudflare DNS API token provided."; \
+		exit 1; \
+	else \
+		CLOUDFLARE_DNS_API_TOKEN=$$cf_dns_token_input; \
+		echo "Cloudflare DNS API token successfully set."; \
+	fi
+endef
+else
+  CF_DNS_TOKEN_PROMPT=@echo "Using provided Cloudflare DNS API token."
+endif
+
 # Environment setup target
 .PHONY: set-env
 set-env:
 	$(DOMAIN_PROMPT)
 	$(PASSWORD_PROMPT)
 	$(CF_API_TOKEN_PROMPT)
+	$(CF_EMAIL_PROMPT)
+	$(CF_DNS_TOKEN_PROMPT)
 	@echo "Final Domain Name: $(DOMAIN_NAME)"
 	@echo "Final Hashed Password: $(HASHED_PASSWORD_ENV_VAR)"
 	@echo "Final Cloudflare API Token: $(CLOUDFLARE_API_KEY)"
+	@echo "Final Cloudflare Email: $(CLOUDFLARE_EMAIL)"
+	@echo "Final Cloudflare DNS API Token: $(CLOUDFLARE_DNS_API_TOKEN)"
 
 # Task to create acme.json and set correct permissions
 .PHONY: create-acme
@@ -79,7 +121,12 @@ create-acme:
 .PHONY: run-traefik
 run-traefik: create-acme set-env
 	@echo "Running Traefik with domain $(DOMAIN_NAME)..."
-	@DOMAIN_NAME=$(DOMAIN_NAME) HASHED_PASSWORD_ENV_VAR=$(HASHED_PASSWORD_ENV_VAR) CLOUDFLARE_API_KEY=$(CLOUDFLARE_API_KEY) docker compose up -d
+	@DOMAIN_NAME=$(DOMAIN_NAME) \
+	HASHED_PASSWORD_ENV_VAR=$(HASHED_PASSWORD_ENV_VAR) \
+	CLOUDFLARE_API_KEY=$(CLOUDFLARE_API_KEY) \
+	CLOUDFLARE_EMAIL=$(CLOUDFLARE_EMAIL) \
+	CLOUDFLARE_DNS_API_TOKEN=$(CLOUDFLARE_DNS_API_TOKEN) \
+	docker compose up -d
 
 # Full setup to set environment, create acme.json, and run Traefik
 .PHONY: setup
